### ISSUE TITLE
Backend criar Conta

### ISSUE THREAD

**Issue by nickmoura** [RoutinelyOrganization/routinely-api#11]
https://docs.google.com/document/d/1aJ_j1xtkFcDyY-aBpdVbGYJ14XhDTHRN/edit

**Comment by medeirosdev** [comment]
## Criar Conta - Como fazer?

- Primeiramente crie funções que retornem o usuário pelo email do banco de dados ( isso será útil no Login )
- Crie funções de Validação de registro( validar se o email e a senha são válidos )
- Exemplo de função para cadastrar

static async createUser(req: Request, res: Response){
       
        const { name, email,  username, confirmpassword , password} = req.body
        
        const validation = validationsUser.RegisterValidation(name, email, username , password , confirmpassword)

        if(validation.length !== 0){
            return res.status(501).json({ message: validation })
        }
        ==== // Faça as criptografias dos dados com Sha256 // =====
        const salt = Auth.new_salt(saltLenght)
        const SHAPass = Auth.sha256(password + salt)
        const SHAemail = Auth.sha256(email)

        const AccountCreated = {
            name: name,
            email: SHAemail,
            username: username,
            salt: salt,
            password: SHAPass,
        }
      // Esse é um exemplo usando sequelize // 
        try{
            const save = await UserCredentials.create(AccountCreated);
            res.status(200).json({message: "Deu certo"})
        }catch (error: any) {
            res.status(500).json({ message: error })
        }  
    } 


## Resumo
Pegar infos do Form
Tratar as Infos
Salvar a Info
