### ISSUE TITLE
Esqueci a senha - Redefinir e reenviar senha

### ISSUE THREAD

**Issue by nickmoura** [RoutinelyOrganization/routinely-api#12]
https://docs.google.com/document/d/1tJMXDIZwOcnZkJbLA2W_xO4dQ3zpgINu/edit

**Comment by medeirosdev** [comment]
## Alterar Senha - Como fazer ?

-  Crie uma função que pegue o usuário pelo ID
- Crie uma função que altere o dado { senha } no banco de dados com uma nova senha
-  Faça a função de alterar a senha ( Não se preocupar com email nem autentição, puramente a função )

- Lembre-se de usar as mesmas tratações da senha normal!

static async TrocarSenha() { 

const newPass = req.body.newPass

const id = req.body.id

const user = usermodel.find(id)

const newuser = {
pass : newPass
}

try{
 usermodel.save(newuser, where id = id)
}

}

**Comment by huilianni** [comment]
Falta:

A redefinição de senha para receber por SMS, que vai ficar para a próxima sprint.

**Comment by lucascda** [comment]
O que precisa ser feito, caso fique pra próxima sprint:
- Fazer o processo descrito nesse card, mas além de usar o e-mail também usar o telefone do usuário para o envio do SMS.
