### ISSUE TITLE
Enviar código de verificação de acesso

### ISSUE THREAD

**Issue by nickmoura** [RoutinelyOrganization/routinely-api#13]
https://docs.google.com/document/d/10EYyCE27JLvWk0_skOfzLOQ9K01wVXQ0/edit

**Comment by huilianni** [comment]
Se relaciona com a redefinição de senha.

Falta:

integração com o SMS, que ficará para a segunda sprint.

**Comment by lucascda** [comment]
O que precisa ser feito, caso fique pra próxima sprint:
- Adicionar telefone do usuário na model Account
- Se preocupar com a adição do telefone no processo de criação de conta
- Fazer o processo descrito nesse card, levando em consideração a integração de alguma ferramenta de envio de SMS.
