### ISSUE TITLE
Autenticar usuário

### ISSUE THREAD

**Issue by nickmoura** [RoutinelyOrganization/routinely-api#14]
https://docs.google.com/document/d/1Y1FBWvcw2kvFnTb2ZgDXaNwUBVmUwvEg/edit

**Comment by medeirosdev** [comment]
## Login Usuário - Como fazer??

- Capture o Email e a senha pelo req.body
- valide e trate essas informações ( com criptografia e validação de caracteres)
- use a função de retornar o usuário pelo email e pegue o user
- verifique se a senha bate
- se sucesso -> Logado
- trate cada erro com uma resposta diferente

**Comment by huilianni** [comment]
Falta apenas a validação de sessão e atualização de sessão.
