### ISSUE TITLE
API - Home

### ISSUE THREAD

**Issue by viniciuscosmome** [RoutinelyOrganization/routinely-api#21]

**Comment by veronicasvalerio** [comment]
https://docs.google.com/document/d/13ACyPt4TEiCeUUXZub7gobAkG3v8P7MUUyvuT7scQmQ/edit

**Comment by viniciuscosmome** [comment]
Concluído o logoff e a query para buscar tarefas do usuário.
Configurações e metas foram separadas pela PM e ficaram para a próxima sprint.

**Comment by lilianekassab** [comment]
@viniciuscosmome e @veronicasvalerio  Essa API está disponibilizada no git? porque eu fiz pull e não tenho na branch develop não aparece essa API, e as outras referentes as TASKs não está funcionando.



![Image](https://github.com/RoutinelyOrganization/routinely-api/assets/139177831/09b682c1-084e-40b0-884d-a3300364e77e)

**Comment by lilianekassab** [comment]
http://localhost:3000/#/default/TaskController_create


![Image](https://github.com/RoutinelyOrganization/routinely-api/assets/139177831/79cebbca-51c0-421d-9687-7de9eb8d7469)



![Image](https://github.com/RoutinelyOrganization/routinely-api/assets/139177831/d2e0f23b-9ac3-4f6a-8ec4-4742e1e3e45c)

**Comment by viniciuscosmome** [comment]
@lilianekassab 

verifica se sua branch está atualizada com a ultima versão. usa o comando git log e verifica se o último commit é:
"Merge pull request #35 from Whoj01/develop"

**Comment by lilianekassab** [comment]
PS C:\Projetos\routinely-api> git log
commit 50d0de420996543291a57142209353b400da00c7 (HEAD -> develop, origin/develop, origin/HEAD)
Merge: 1130e01 846ce9b
Author: Lucas <43433070+lucascda@users.noreply.github.com>
Date:   Wed Aug 30 18:05:11 2023 -0300

    Merge pull request #35 from Whoj01/develop

    Fix: removing forgotten console log on mailing service

commit 846ce9bfcb1614d1736d83540bdb157ffe502e5e
Author: josue dias <josueneto9@hotmail.com>
Date:   Wed Aug 30 13:07:41 2023 -0300

    Fix: removing forgotten console log on mailing service

commit 1130e01868f0c5df09bb86bb26e8d39b655967b2
Merge: f0218b8 6c26d93
Author: Cinthia <62577303+cinthiams@users.noreply.github.com>
Date:   Mon Aug 28 15:36:49 2023 -0300

**Comment by viniciuscosmome** [comment]
@lilianekassab , corrigindo*

Este erro "401" acontece por que você não tem permissão para realizar isso, você precisa deletar o banco de dados ou criar uma nova conta para poder testar.

**Comment by viniciuscosmome** [comment]
enviado pra homologação
