### ISSUE TITLE
API - Adicionar tarefa

### ISSUE THREAD

**Issue by viniciuscosmome** [RoutinelyOrganization/routinely-api#22]

**Comment by veronicasvalerio** [comment]
https://docs.google.com/document/d/1kVnw-RtmIUDTp5737F74iieK3pCvBL8HH1zn8x67ax8/edit

**Comment by huilianni** [comment]
@viniciuscosmome 

Falta exigir que o usuário esteja logado pra adicionar a tarefa. Se possível documentar como fazer isso no código.

**Comment by viniciuscosmome** [comment]
Feito
https://github.com/RoutinelyOrganization/.github-private/issues/28

**Comment by viniciuscosmome** [comment]
enviado pra homologação
