### ISSUE TITLE
Método de autenticação e autorização

### ISSUE THREAD

**Issue by lucascda** [RoutinelyOrganization/routinely-api#3]
Conversei com o @viniciuscosmome hoje e ficou a dúvida sobre como vamos fazer autenticação e autorização em múltiplos dispositivos. Vamos usar a abordagem de JWT mesmo ou algo mais pro lado de sessões em banco? Ele chegou a usar o conceito de sessões mas o JWT é auto-contido, daí ficou a dúvida.

Acabei encontrando uma possível solução pra fazer o fluxo em JWT: [https://stackoverflow.com/questions/72511998/how-to-manage-multi-device-simultaneous-login-with-jwt-tokens](url)

Qual sua opinião @medeirosdev ? @viniciuscosmome se quiser complementar algo, fique a vontade.

**Comment by medeirosdev** [comment]
Estava lendo o link e gostei bastante da ideia, inclusive podemos discutir uma forma de criptografar o token, sem ser por hash, eu tenho algumas criptografias prontas aqui https://github.com/medeirosdev/CryptoriumHex-12By2/tree/master , inclusive, depois precisamos discutir a criptografia do _email_ , já que o Rick falou que talvez iremos usar o email para notificações etc.
Por hora, gostei da solução e podemos discutir pra implementar

**Comment by lucascda** [comment]
@medeirosdev Desculpa a pergunta, mas criptografar o jwt é realmente necessário? Isso não tornaria o processo de autenticação e autorização lento, já que a aplicação teria que passar por todas as etapas de criptografia?

**Comment by medeirosdev** [comment]
Provavelmente pode ficar mais lento , sim
Podemos testar, vamos fazer uma versão sem criptografia, e depois eu testo com uma criptografia simples, pode ser que fique mais lento, mas não tão lento a ponto de prejudicar a aplicação. De qualquer forma, vamos fazer os testes pra achar a melhor solução.

**Comment by viniciuscosmome** [comment]
@lucascda Gostei do artigo, porém a gente tem de volta a questão das permissões no payload do token. "Como atualizar as permissões que estão no token do cliente que ainda é válido?", Pelo vi, não tem nada que se refira a questão do token ser revalidado caso as permissões mudem.

**Comment by lucascda** [comment]
@viniciuscosmome Sua indagação é muito pertinente, ainda vamos ter que lidar com isso. O próprio "expiration time" do jwt já ajuda um pouco nisso, mas ainda não resolve totalmente.

**Comment by viniciuscosmome** [comment]
@lucascda  Eu sugiro o modo de sessões com cache e sincronizando com um DB que contenha somente as sessões. Assim, a gente pode controlar quantas sessões simultâneas estão ativas, remover/alterar o acesso, excluir todas as sessões do usuário relativo quando alterar a senha, tudo isso e sem depender do tempo de expiração de um token. O controle de acesso seria bem melhor controlado pelo servidor.

Quanto a quantidade de cache, isso terá que ser analisado, mas somente as sessões ficarão nesse DB (chave da sessão, chave para atualização, id da conta e suas permissões), por enquanto.
