### ISSUE TITLE
Metas API

### ISSUE THREAD

**Issue by veronicasvalerio** [RoutinelyOrganization/routinely-api#43]
https://docs.google.com/document/d/1DCz6nHf2l5mOIBPGw6IYIuLypHcfZieernooT9hG_Us/edit

**Comment by lucascda** [comment]
A feature foi terminada e estamos esperando alguém do time de QA para progredir com o card.

@carol-schmidt   @lilianekassab

**Comment by lilianekassab** [comment]
@lucascda  consegue me ajudar?
estou fazendo os testes, mas não consigo executar a API


![Image](https://github.com/RoutinelyOrganization/routinely-api/assets/139177831/528fc3ee-f247-403d-99dd-c07446b29dd8)

obtenho o seguinte:


![Image](https://github.com/RoutinelyOrganization/routinely-api/assets/139177831/1c0f9198-b891-481a-8fff-cad5ddb7f387)

**Comment by carol-schmidt** [comment]
Testada e validada.



![Image](https://github.com/RoutinelyOrganization/routinely-api/assets/88946459/8db3d754-253d-4fff-9563-f79c6bc29794)
