### ISSUE TITLE
Revisar tag add task

### ISSUE THREAD

**Issue by hartmannjean** [RoutinelyOrganization/routinely-api#50]

**Comment by viniciuscosmome** [comment]
@RoutinelyOrganization/mobile podem descrever o problema para eu revisar?

**Comment by carol-schmidt** [comment]
@OdisBy @viniciuscosmome vocês já conversaram sobre o problema e está para teste mesmo?

**Comment by viniciuscosmome** [comment]
@carol-schmidt sim, esse card já está para ser testado, já foi feito o merge na branch develop das mudanças.

- [x] fixado o erro das tags que estavam como se fossem as categorias.
- [x] criado as categorias que não existiam.

PR #60

**Comment by carol-schmidt** [comment]
@viniciuscosmome a principio finalizei o teste desta task, se puder subir para eu poder testar a parte de mobile que está bloqueado

**Comment by viniciuscosmome** [comment]
@carol-schmidt Deploy de homologação feito
