### ISSUE TITLE
validar código de alteração de senha - api

### ISSUE THREAD

**Issue by viniciuscosmome** [RoutinelyOrganization/routinely-api#62]
Criar um ponto de acesso para a validação do código que é recebido no e-mail quando a redefinição de senha é pedida.

**Comment by huilianni** [comment]
@Rennanbarao0 favor inserir as informações e prazo para transferirmos o card para a próxima coluna (In Review),

**Comment by viniciuscosmome** [comment]
@RoutinelyOrganization/quality-assurance 

> [!note]\
> Só movendo as informações do @Rennanbarao0 para cá

---

# Documentação sobre o processo de redefinição de senha no Routnely

Neste documento você encontrará informações detalhadas sobre como usar o serviço de `redefinir senha` no Routnely.

---

⚠️ **Insira os dados do seu usuário cadastrado para realizar os testes na aplicação.**

---

- Se autentique fazendo login na aplicação

```http
POST /auth
```

```json
{
  "email": "routnely@email.com",
  "password": "@exemple",
  "remember": true
}
```

![Image](https://github.com/RoutinelyOrganization/routinely-api/assets/48590313/1fb13baf-f24a-4864-a4f8-e541f45fdedd)

---

- Solicite a redefinição de senha informando o `email` na rota `auth/resetpassword`

```http
POST /auth/resetpassword
```

```json
{
  "email": "routnely@email.com"
}
```

![Image](https://github.com/RoutinelyOrganization/routinely-api/assets/48590313/cd566e1b-c13c-40e3-b10f-390f96264a47)

Ao obter um retorno 201 na requisição, salve o `accountId`, precisaremos dele posteriormente.

---

Após solicitação no `resetpassword`, verifique o código recebido por e-mail.

- Acesse `mailtrap.io` e faça login.

![Image](https://github.com/RoutinelyOrganization/routinely-api/assets/48590313/2a3cf034-c850-4b21-993c-70a9383d94c9)

---

Acesse `My Inbox`

![Image](https://github.com/RoutinelyOrganization/routinely-api/assets/48590313/169f6b0c-25bf-4c27-a392-84b020c8d520)

Ao chegar no Inbox, localize o e-mail informado que contém o código.

---

- Para validar o código recebido vá até a rota `auth/validatecode` e informe o `code` e o `accountId`

```http
POST /auth/validatecode
```

```json
{
  "code": "123456",
  "accountId": "string-accountId"
}
```

`Em caso de sucesso:`

![Image](https://github.com/RoutinelyOrganization/routinely-api/assets/48590313/c5545e33-d6ba-4c3b-8d28-63de08061cc4)

`Em caso de erro:`

![Image](https://github.com/RoutinelyOrganization/routinely-api/assets/48590313/e4615b02-8a5e-41b1-95e3-4f11572a129d)

---

- Após o código ser validado, insera o mesmo código na rota `auth/changepassword` para efetivar a mudança de senha

Será necessário informar o `password` (a nova senha desejada), o `code` e o `accountId` do seu usuário

```http
PUT /auth/changepassword
```

```json
{
  "password": "nova-senha",
  "code": "123456",
  "accountId": "string-accountId"
}
```

![Image](https://github.com/RoutinelyOrganization/routinely-api/assets/48590313/3bd1f859-7da2-4771-80a7-82f10e9c64e6)

---

Após todos os passos citados acima, a sua nova senha já teria sido redefinida.

Realize o login novamente com a nova senha criada.

**Comment by lilianekassab** [comment]
Conseguimos fazer os testes desta forma faz sentido para  você? @Rennanbarao0 

Evidência de teste:


![Image](https://github.com/RoutinelyOrganization/routinely-api/assets/139177831/b06fbb22-3f5a-4321-b554-1464ef32301f)

**Comment by Rennanbarao0** [comment]
@lilianekassab, vi que na hora de fazer a solicitação foi inserido o **repeatpassowrd**, isso não é mais necessário. 

Pode enviar apenas: 

- accoundId
- password
- code

**Comment by ellensilva** [comment]
Oi @Rennanbarao0!
Temos chamar a rota auth/validatecode mas ela retornour 404 - not found
Segue o cURL que a gente testou:
``curl --location 'https://routinely-api-dev.onrender.com/auth/validatecode' \
--header 'Content-Type: application/json' \
--data '{
  "code": "121049",
  "accountId":"51ceb5e2-a8c8-495e-9bb1-f1095fa000c6"
}'``

Evidencia:


![Image](https://github.com/RoutinelyOrganization/routinely-api/assets/3883834/0669cb5a-3cf1-4224-a90e-30c1544a87b7)

**Comment by Rennanbarao0** [comment]
@ellensilva, podemos marcar uma call para ver sobre isso? Coisa rápida mesmo!

**Comment by viniciuscosmome** [comment]
@lilianekassab  @ellensilva , essas alterações não foram homologadas. As requisições que vocês mandaram foram para a API de homologação.

**Comment by viniciuscosmome** [comment]
> _manter o card aberto até a homologação_

**Comment by lilianekassab** [comment]
Evidências de Testes

**Validação bem sucedida. ok**

Curl

curl -X 'POST' \
  'http://localhost:3000/auth/validatecode' \
  -H 'accept: */*' \
  -H 'Content-Type: application/json' \
  -d '{
  "code": "128274",
  "accountId": "5e41a287-cc10-494a-83bc-e2c026a821ca"
}'


![Image](https://github.com/RoutinelyOrganization/routinely-api/assets/139177831/1df29730-a044-4f77-b98a-fc37fe0bc1f2)

**Senha alterada com sucesso ok**

Curl

curl -X 'PUT' \
  'http://localhost:3000/auth/changepassword' \
  -H 'accept: */*' \
  -H 'Content-Type: application/json' \
  -d '{
  "password": "Teste2024!",
  "code": "251590",
  "accountId": "5e41a287-cc10-494a-83bc-e2c026a821ca"

}'


![Image](https://github.com/RoutinelyOrganization/routinely-api/assets/139177831/df4e93b0-23df-4795-9896-5905fbbaf117)

**Comment by viniciuscosmome** [comment]
deploy feito
