### ISSUE TITLE
BUG - Autenticação

### ISSUE THREAD

**Issue by viniciuscosmome** [RoutinelyOrganization/routinely-api#70]
## Bug
Usuários conseguem realizar alterações em tarefas de outros usuários.

**Comment by viniciuscosmome** [comment]
Causa encontrada: a chave de acesso de ultimo usuário que fez login estava salva globalmente.

**Comment by viniciuscosmome** [comment]
@RoutinelyOrganization/quality-assurance 

O erro acontecia após um usuário realizar o login, depois disso, o próximo usuário poderia realizar requisições sem enviar a chave de acesso.

---
## Unhappy path

1. Realize o login normalmente

```md
POST /auth

{ email, password }
```

2. Acesse uma rota protegida pelo menos uma vez com a chave de acesso

```md
GET /tasks
Authorization: Bearer acceesToken
```

3. Agora remova o cabeçalho "Authorization" da requisição e tente criar uma task

```md
POST /tasks
```

Aqui é onde a aplicação estava permitindo a ação. Isso não era pra acontecer.

## Happy path

Atualize sua branch com a nova versão da "develop" e realize os mesmos teste. Dessa vez, a aplicação deve bloquear as ações de usuários sem o cabeçalho de autenticação.

**Comment by lilianekassab** [comment]
Segue:
Curl

curl -X 'POST' \
  'http://localhost:3000/tasks' \
  -H 'accept: */*' \
  -H 'Content-Type: application/json' \
  -d '{
  "name": "Uma atividade normal teste ",
  "description": "Descrição personalizada da atividade",
  "date": "2024-04-01 04:20",
  "priority": "low",
  "tag": "application",
  "category": "personal"
}'


![Image](https://github.com/RoutinelyOrganization/routinely-api/assets/139177831/2eefa9e9-99a6-4360-9d0e-21406731c72f)

Está respondendo como o esperado.

@viniciuscosmome agora temos essa resposta. Isso faz sentido para você?

**Comment by viniciuscosmome** [comment]
@lilianekassab . Sim, esse é o comportamento esperado.

**Comment by viniciuscosmome** [comment]
deploy na homologação
